# Class Task 2
A = [[2, -1, 3], [0, 4, 1]]
B = [[1, 2], [-2, 0], [5, -3]]
Given the matrices:
1. (a) Number of rows and columns in each matrix.
2. (b) Determine whether the matrices can be multiplied. if so specify whether its (AB),(BA), or both
3. (c) If defined, compute the resulting matrices using NumPy and explain the results.
4. (Bonus) What will be the dimensions of the product matrix if the multiplication is valid

In [3]:
import numpy as np

# Construct matrices A and B as given in the task
A = np.array([[2, -1, 3], [0, 4, 1]])
B = np.array([[1, 2], [-2, 0], [5, -3]])

# Print matrices to verify
print('A =')
print(A)
print('B =')
print(B)

A =
[[ 2 -1  3]
 [ 0  4  1]]
B =
[[ 1  2]
 [-2  0]
 [ 5 -3]]


In [10]:
# (a) Identify number of rows and columns for each matrix
print('(a) Shapes:')
print('A shape (rows, cols):', A.shape)
print('B shape (rows, cols):', B.shape)

# (b) Determine whether the matrices can be multiplied. if so specify whether its (AB),(BA), or both
can_AB = A.shape[1] == B.shape[0]  # inner dims must match (3 == 3)
can_BA = B.shape[1] == A.shape[0]  # inner dims must match (2 == 2)
print('\n(b) Multiplication compatibility:')
print('Can compute AB?', can_AB)
print('Can compute BA?', can_BA)

# (c) Compute AB and BA when defined and document the results
if can_AB:
    AB = A @ B  # Matrix multiplication using @ operator
    print('\n(c) AB =')
    print(AB)
    print('AB shape:', AB.shape)
else:
    print('\nAB is not defined')

if can_BA:
    BA = B @ A  # Matrix multiplication using @ operator
    print('\nBA =')
    print(BA)
    print('BA shape:', BA.shape)
else:
    print('\nBA is not defined')

# Bonus: What will be the dimensions of the product matrix if the multiplication is valid
print('\n(Bonus) Product dimensions:')
print('AB dimensions: A(2,3) × B(3,2) = result is (2,2)')
print('BA dimensions: B(3,2) × A(2,3) = result is (3,3)')
print('Rule: For matrix multiplication C = P × Q, if P is (m,n) and Q is (n,k), then C is (m,k)')

(a) Shapes:
A shape (rows, cols): (2, 3)
B shape (rows, cols): (3, 2)

(b) Multiplication compatibility:
Can compute AB? True
Can compute BA? True

(c) AB =
[[19 -5]
 [-3 -3]]
AB shape: (2, 2)

BA =
[[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
BA shape: (3, 3)

(Bonus) Product dimensions:
AB dimensions: A(2,3) × B(3,2) = result is (2,2)
BA dimensions: B(3,2) × A(2,3) = result is (3,3)
Rule: For matrix multiplication C = P × Q, if P is (m,n) and Q is (n,k), then C is (m,k)


## Final answers (summary)
- (a) A is 2 × 3 (2 rows, 3 columns). B is 3 × 2 (3 rows, 2 columns).
- (b) Both products AB and BA are defined because:
  - For AB: A's columns (3) = B's rows (3)
  - For BA: B's columns (2) = A's rows (2)
- (c) The computed matrices are:
  - AB is a 2 × 2 matrix 
  - BA is a 3 × 3 matrix
  - Numerical results are shown in the code cells above
- (Bonus) Product dimensions follow the rule: (m,n) × (n,k) = (m,k)
  - AB: (2,3) × (3,2) = (2,2)
  - BA: (3,2) × (2,3) = (3,3)