# Linear Algebra Case Study

## Problem Setup
We have the scores of 4 students in 3 subjects (Mathematics, English, Science):
| Student   | Math | English | Science |
|-----------|------|---------|---------|
| Student 1 |  80  |   70    |   90    |
| Student 2 |  60  |   85    |   75    |
| Student 3 |  95  |   88    |   92    |
| Student 4 |  70  |   60    |   65    |

## student matrix
student_data = 	[[80, 70, 90],
				[60, 85, 75],
				[95, 88, 92],
				[70, 60, 65]]

In [2]:
import numpy as np

In [ ]:
# 3.1 Representing Data as a Matrix
student_data = 	np.array([[80, 70, 90],[60, 85, 75],[95, 88, 92],[70, 60, 65]])
print("Student Data Matrix:")
print(student_data)

In [5]:
# 3.2 Total Scores per Student (Vector Addition)
total_scores = np.sum(student_data, axis=1)
print("\nTotal Scores per Student:")
print(total_scores)


Total Scores per Student:
[240 220 275 195]


In [7]:
# Applying Weights (Scalar Multiplication)
weights = np.array([2, 1, 1])  # Math, Science, English weights
weighted_scores = student_data * weights
print("\nWeighted Scores:")
print(weighted_scores)


Weighted Scores:
[[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]


In [9]:
# 3.4 Average Score per Subject (Matrix Operations)
average_scores = np.mean(student_data, axis=0)
print("\nAverage Scores per Subject:")
print(average_scores)


Average Scores per Subject:
[76.25 75.75 80.5 ]


In [11]:
# Final Grades using Matrix Multiplication
final_grades = np.dot(student_data, weights) / np.sum(weights)
print("\nFinal Grades:")
print(final_grades)


Final Grades:
[80.   70.   92.5  66.25]


In [12]:
# 3.6 Comparing Students (Vector Subtraction)
comparison = student_data[0] - student_data[1]
print("\nComparison between Student 1 and Student 2:")
print(comparison)


Comparison between Student 1 and Student 2:
[ 20 -15  15]
