### DEFINE MATRICE A AND B


In [1]:
import numpy as np
A = np.array([[2, -1],
              [0, 3]])

B = np.array([[1, 4],
              [-2, 5]])

# Define scalars
c = 2
d = 3

### SCALAR MULTIPLICATION

In [5]:
cA = c * A
print("cA =\n", cA)

dB = d * B
print("dB =\n", dB)

# (c + d) * A
cd_A = (c + d) * A
print("(c + d)A =\n", cd_A)

cA =
 [[ 4 -2]
 [ 0  6]]
dB =
 [[ 3 12]
 [-6 15]]
(c + d)A =
 [[10 -5]
 [ 0 15]]


### ASSOCIATIVE OF SCALAR MULTIPLICATION   (c * d)A == c * (dA)

In [6]:
cdA = (c * d) * A
print("(c * d)A =\n", cdA)

dA = d * A
cdA_1 = c * dA
print("c(dA) =\n", cdA_1)

(c * d)A =
 [[12 -6]
 [ 0 18]]
c(dA) =
 [[12 -6]
 [ 0 18]]


### DISTRIBUTIVITY MATRIX ADDITTION  c(A + B) == cA + cB

In [4]:
A_plus_B = A + B
c_A_plus_B = c * A_plus_B
print("c(A + B) =\n", c_A_plus_B)

cB = c * B
cA_plus_cB = cA + cB
print("cA + cB =\n", cA_plus_cB)

c(A + B) =
 [[ 6  6]
 [-4 16]]
cA + cB =
 [[ 6  6]
 [-4 16]]



### Distributivity over scalar addition (c + d)A == cA + dA

In [7]:
cdA_again = cA + dA
print("cA + dA =\n", cdA_again)


cA + dA =
 [[10 -5]
 [ 0 15]]



### Transposes

In [8]:

A_T = A.T
print("Transpose of A:\n", A_T)

B_T = B.T
print("Transpose of B:\n", B_T)

Transpose of A:
 [[ 2  0]
 [-1  3]]
Transpose of B:
 [[ 1 -2]
 [ 4  5]]
