# Class task 3
- let A = [[2, 1],[0,3]]
- let B = [[1, 4],[-2,5]]
- let c = 2
- let d = 3

- (a) Compute the following (cA),  (dB) and (c + d)A
- (b) Using the result gotten, Verify the Scalar multiplication properties
- (C) Find the transpose of both matrices
- (d) Check if (A) and (B) are invertible by computing their determinants, if they are invertible find A^(-1) and B^(-1)

In [2]:
import numpy as np

A = np.array([[2, 1],[0,3]])
B = np.array([[1, 4],[-2,5]])
c = 2
d = 3

print("A: =\n", A)
print("B: =\n", B)
print("c: =\n", c)
print("d: =\n", d)

A: =
 [[2 1]
 [0 3]]
B: =
 [[ 1  4]
 [-2  5]]
c: =
 2
d: =
 3


In [3]:
# Compute the following (cA),  (dB) and (c + d)A
cA = c * A
dB = d * B
cdA = (c + d) * A

print("cA =\n", cA)
print("dB =\n", dB)
print("cdA =\n", cdA)

cA =
 [[4 2]
 [0 6]]
dB =
 [[ 3 12]
 [-6 15]]
cdA =
 [[10  5]
 [ 0 15]]


In [4]:
# Using the result gotten, Verify the Scalar multiplication properties

if np.array_equal(cA + dB, cdA):
	print("The scalar multiplication properties hold: cA + dB = (c + d)A")

In [8]:
# Find the transpose of both matrices

A_T = A.T
B_T = B.T

print("A^T =\n", A_T)
print("B^T =\n", B_T)

A^T =
 [[2 0]
 [1 3]]
B^T =
 [[ 1 -2]
 [ 4  5]]


In [9]:
# Check if (A) and (B) are invertible by computing their determinants, if they are invertible find A^(-1) and B^(-1)
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

if det_A != 0:
    A_inv = np.linalg.inv(A)
    print("A^(-1) =\n", A_inv)
else:
    print("A is not invertible")

if det_B != 0:
    B_inv = np.linalg.inv(B)
    print("B^(-1) =\n", B_inv)
else:
    print("B is not invertible")

A^(-1) =
 [[ 0.5        -0.16666667]
 [ 0.          0.33333333]]
B^(-1) =
 [[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
