### 3.1 Representing Data as a Matrix

In [71]:
import numpy as np
student_matrix =  np.array([[80, 70, 90], 
                            [60, 85, 75], 
                            [95, 88, 92], 
                            [70, 60, 65]]) 

### 3.2 Total Scores per Student (Vector Addition) 

In [72]:

student_matrix_sum = np.sum(student_matrix, axis=1)
print("\nTotal scores per student:")

for i,total in enumerate(student_matrix_sum): 
    print(f"student_{i+1} total score: {total}")



Total scores per student:
student_1 total score: 240
student_2 total score: 220
student_3 total score: 275
student_4 total score: 195


### 3.3 Applying Weights (Scalar Multiplication)

In [73]:
weight = [2, 1, 1]
weighted_scores1 = student_matrix * weight
print(weighted_scores1)

[[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]


### 3.4 Average Score per Subject (Matrix Operations) 

In [74]:

subject_matrix_mean = np.mean(student_matrix, axis=0)
subjects2 = ["Mathematics", "English Language", "Science"]
# print("\n-- Student's Subjects Average Scores--")
for i, average1 in enumerate(subject_matrix_mean):
    print(f"{subjects2[i]} Average score: {average1}")

Mathematics Average score: 76.25
English Language Average score: 75.75
Science Average score: 80.5


### 3.5 Final Grades using Matrix Multiplication 

In [75]:
weights_mat_mult = np.array([0.5, 0.3, 0.2]) 

final_grades = student_matrix * weights_mat_mult,
print(final_grades)

(array([[40. , 21. , 18. ],
       [30. , 25.5, 15. ],
       [47.5, 26.4, 18.4],
       [35. , 18. , 13. ]]),)


### 3.6 Comparing Students (Vector Subtraction) 

In [76]:
student1 = student_matrix[1]
student2 = student_matrix[2]

comparison = student1 - student2
print("Student 1 - Student 2:\n", comparison)


for i, diff in enumerate(comparison):
    subject = ["Math", "English", "Science", "History"][i]
    if diff > 0:
        print(f"Student 1 scored higher in {subject} by {diff} points.")
    elif diff < 0:
        print(f"Student 2 scored higher in {subject} by {-diff} points.")
    else:
        print(f"Both students scored the same in {subject}.")

Student 1 - Student 2:
 [-35  -3 -17]
Student 2 scored higher in Math by 35 points.
Student 2 scored higher in English by 3 points.
Student 2 scored higher in Science by 17 points.


### Create a 5×4 matrix of scores and calculating the student's total score and average per subject

In [ ]:


student_scores = np.array([[80, 70, 90, 60],  
                   [85, 75, 95, 65],  
                   [78, 82, 88, 70], 
                   [92, 68, 84, 75],  
                   [76, 80, 85, 72]])

print(student_scores)

 
student_totals = np.sum(student_scores, axis=1)
print("\nTotal scores per student:")

for i,total in enumerate(student_totals): 
    print(f"student_{i+1} total score: {total}")


subject_averages = np.mean(student_scores, axis=0)
subjects = ["Mathematics", "English Language", "Chemistry", "Pyhsics"]
print("\n-- Student's Subjects Average Scores--")
for i, average in enumerate(subject_averages):
    print(f" {subjects[i]} Average score: {average}")




[[80 70 90 60]
 [85 75 95 65]
 [78 82 88 70]
 [92 68 84 75]
 [76 80 85 72]]

Total scores per student:
student_1 total score: 300
student_2 total score: 320
student_3 total score: 318
student_4 total score: 319
student_5 total score: 313

-- Student's Subjects Average Scores--
 Mathematics Average score: 82.2
 English Language Average score: 75.0
 Chemistry Average score: 88.4
 Pyhsics Average score: 68.4


###  scalar multiplication and recomputing totals 

In [36]:

weighted_scores = student_scores.copy()
weighted_scores[:, 2] *= 3  


weighted_totals = np.sum(weighted_scores, axis=1)
print("Weighted total scores per student (Science x3):\n")


for i,wtotal in enumerate(weighted_totals): 
    print(f"student_{i+1} Weigthed score: {wtotal}")


Weighted total scores per student (Science x3):

student_1 Weigthed score: 480
student_2 Weigthed score: 510
student_3 Weigthed score: 494
student_4 Weigthed score: 487
student_5 Weigthed score: 483


### Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using matrix multiplication

In [ ]:

weights = np.array([0.4, 0.2, 0.3, 0.1]) 

final_grades = student_scores * weights,
print(final_grades)




(array([[32. , 14. , 27. ,  6. ],
       [34. , 15. , 28.5,  6.5],
       [31.2, 16.4, 26.4,  7. ],
       [36.8, 13.6, 25.2,  7.5],
       [30.4, 16. , 25.5,  7.2]]),)


###  Compare Student 3 and Student 4 using vector subtraction. Who performed better in each subject? 

In [ ]:
student3 = student_scores[2]
student4 = student_scores[3]

comparison = student3 - student4
print("Student 3 - Student 4:\n", comparison)


for i, diff in enumerate(comparison):
    subject = ["Math", "English", "Science", "History"][i]
    if diff > 0:
        print(f"Student 3 scored higher in {subject} by {diff} points.")
    elif diff < 0:
        print(f"Student 4 scored higher in {subject} by {-diff} points.")
    else:
        print(f"Both students scored the same in {subject}.")


Student 3 - Student 4:
 [-14  14   4  -5]
Student 4 scored higher in Math by 14 points.
Student 3 scored higher in English by 14 points.
Student 3 scored higher in Science by 4 points.
Student 4 scored higher in History by 5 points.
