#Task 1

In [1]:
import numpy as np

arr = np.random.randint(1, 51, size=(6,6))
print(arr)

[[36  4 45 23 19 24]
 [46  5 27 25 47 17]
 [38  4 41 13  1 22]
 [27  4 40 11  3 29]
 [24  2 32 46 13 49]
 [38  3 23 33 42 28]]


#Task 2

In [4]:
row_1 = arr[0] 
row_2 = arr[1]

print(row_1,row_2)


[36  4 45 23 19 24] [46  5 27 25 47 17]


Task3

In [5]:
arr3d = arr.reshape(3, 2, 6) 
print(arr3d)

[[[36  4 45 23 19 24]
  [46  5 27 25 47 17]]

 [[38  4 41 13  1 22]
  [27  4 40 11  3 29]]

 [[24  2 32 46 13 49]
  [38  3 23 33 42 28]]]


In [6]:
arr1d = arr3d.flatten()
print(arr1d)

[36  4 45 23 19 24 46  5 27 25 47 17 38  4 41 13  1 22 27  4 40 11  3 29
 24  2 32 46 13 49 38  3 23 33 42 28]


Task 4

In [8]:
id_matrix = np.eye(4)


diag_values = np.arange(10, 50,10)[:4]
np.fill_diagonal(id_matrix, diag_values)
print(id_matrix)

[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


In [ ]:
Task5

In [10]:
num_1 = np.random.randint(1,11, size= (3,4))
print(num_1)

num_2 = np.random.randint(1,11,  size= (4,3))
print(num_2)

multpy = np.matmul(num_1,num_2)
print(multpy)

[[ 5  3  9  8]
 [ 6  3 10  9]
 [ 1  1  1 10]]
[[ 7  1  3]
 [ 2  4 10]
 [ 6  6  7]
 [10  4  8]]
[[175 103 172]
 [198 114 190]
 [115  51 100]]
